on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url

  RunAll:
    needs: [CloneRepo]
    resources:
      instance-type: C5
    inputs:
      repo: CloneRepo.outputs.repo
      stocks_data:
        type: dataset
        id: ds39mbittjyyz2q      # ← your actual dataset ID
    uses: script@v1
    with:
      image: python:3.10
      script: |
        # 1) install deps
        pip install --upgrade pip
        pip install -r /inputs/repo/requirements.txt

        # 2) fetch & save parquet
        python /inputs/repo/ingest.py --data_dir /inputs/stocks_data

        # 3) backtest
        python /inputs/repo/trending_model.py --data_dir /inputs/stocks_data

        # 4) (optional) start API
        uvicorn app:app --host 0.0.0.0 --port 8080
