on:
  github:
    branches:
      only: main

jobs:
  # 1) Clone your GitHub repo
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url

  # 2) Install requirements & run your scripts
  RunAll:
    needs: [CloneRepo]
    inputs:
      repo: CloneRepo.outputs.repo
    resources:
      instance-type: C5
    uses: script@v1
    with:
      # Use a Python image that has pip
      image: python:3.10
      script: |
        # Upgrade pip and install all dependencies
        pip install --upgrade pip
        pip install -r /inputs/repo/requirements.txt

        # Run your ETL, modeling, and API startup (adjust as needed)
        python /inputs/repo/ingest.py
        python /inputs/repo/trending_model.py
        uvicorn app:app --host 0.0.0.0 --port 8080
