on:
  github:
    branches:
      only: main

jobs:
  # 1) clone your code
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url

  # 2) install dependencies
  SetupEnv:
    needs: [CloneRepo]
    resources:
      instance-type: C5
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      image: python:3.10
      script: |
        pip install --upgrade pip
        pip install -r /inputs/repo/requirements.txt

  # 3) pull data, train model, start app
  RunAll:
    needs: [SetupEnv]
    resources:
      instance-type: C5
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      image: python:3.10
      script: |
        python /inputs/repo/ingest.py
        python /inputs/repo/trending_model.py
        uvicorn app:app --host 0.0.0.0 --port 8080
