  RunAll:
    needs: [CloneRepo]
    resources:
      instance-type: C5
    inputs:
      repo: CloneRepo.outputs.repo
      stocks_data:
        type: dataset
        id: ds39mbittjyyz2q   # ← replace with your actual dataset ID
    uses: script@v1
    with:
      image: python:3.10
      script: |
        pip install --upgrade pip
        pip install -r /inputs/repo/requirements.txt

        # make sure ingest writes into /inputs/stocks_data
        python /inputs/repo/ingest.py --data_dir /inputs/stocks_data

        python /inputs/repo/trending_model.py --data_dir /inputs/stocks_data

        uvicorn app:app --host 0.0.0.0 --port 8080

