on:
  github:
    branches:
      only: main   # (or whatever your default branch is)

jobs:
  CloneRepo:
    uses: git-checkout@v1
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    with:
      url: context.event.github.url

  RunAll:
    needs: [CloneRepo]
    uses: script@v1
    resources:
      instance-type: C5
    inputs:
      repo: CloneRepo.outputs.repo
    with:
      image: python:3.10
      script: |
        pip install -r /inputs/repo/requirements.txt
        python /inputs/repo/ingest.py
        python /inputs/repo/trending_model.py
        python /inputs/repo/app.py
