on:
  github:
    branches:
      only: main

jobs:
  Clone:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url

  IngestData:
    needs:
      - Clone
    resources:
      instance-type: C5
    inputs:
      repo: Clone.outputs.repo
    uses: script@v1
    with:
      script: python /inputs/repo/ingest.py

  TrainModel:
    needs:
      - IngestData
    resources:
      instance-type: C5
    inputs:
      repo: Clone.outputs.repo
    uses: script@v1
    with:
      script: python /inputs/repo/trending_model.py

  Serve:
    needs:
      - TrainModel
    resources:
      instance-type: C5
    inputs:
      repo: Clone.outputs.repo
    uses: script@v1
    with:
      script: python /inputs/repo/app.py
      # you can swap out to a container step if you built a Docker image
