version: 1.0

stages:
  # 1. Ingest stage: fetch OHLCV and write to data/history/
  - name: ingest
    image: python:3.9
    commands:
      - pip install alpaca-py pandas
      - python ingest.py

  # 2. Train stage: compute intraday momentum for each symbol
  - name: train
    image: python:3.9
    commands:
      - pip install pandas numpy scikit-learn
      - python trending_model.py \
          --start "$(date -I -d 'today')" \
          --end "$(date -I -d 'today')" \
          --data-dir data/history \
          --out signals.json

  # 3. Serve stage: launch a FastAPI app to return the latest picks
  - name: serve
    image: python:3.9
    command: >
      bash -lc "
        pip install fastapi uvicorn pandas &&
        uvicorn app:app --host 0.0.0.0 --port \$PORT
      "
    port: $PORT
