on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url

  RunAll:
    needs: [CloneRepo]
    resources:
      instance-type: C5
    inputs:
      repo: CloneRepo.outputs.repo
      stocks_data:
        type: dataset
        id: YOUR_DATASET_ID_HERE   # ← swap in your dataset ID
    uses: script@v1
    with:
      image: python:3.10
      script: |
        # 1) load env & install
        pip install --upgrade pip
        pip install -r /inputs/repo/requirements.txt

        # 2) fetch raw data
        python /inputs/repo/ingest.py \
          --symbols AAPL MSFT GOOG \
          --data_dir /inputs/stocks_data

        # 3) run backtests
        python /inputs/repo/trending_model.py --data_dir /inputs/stocks_data

        # 4) optional: start API for on-demand signals
        uvicorn app:app --host 0.0.0.0 --port 8080
